### ISSUE TITLE
Support Expo EAS Updates

### ISSUE THREAD

**Issue by andrewjack-cat** [DataDog/expo-datadog#28]
**Is your feature request related to a problem? Please describe.**
I'd like a simple way of uploading sourcemaps to datadog when creating an Expo EAS Update.

**Describe the solution you'd like**
New command in datadog-ci similar to the codepush command - https://github.com/DataDog/datadog-ci/tree/master/src/commands/react-native#codepush

**Describe alternatives you've considered**
Sentry & expo have this available already - https://github.com/getsentry/sentry-react-native/blob/main/scripts/expo-upload-sourcemaps.js

**Additional context**
https://docs.expo.dev/guides/using-sentry/#usage-with-eas-update

**Comment by louiszawadzki** [comment]
Hi @andrewjack-cat, thanks for reaching out!

This is indeed on our roadmap, we'll let you know once this is available :)

**Comment by andrewjack-cat** [comment]
In the meantime, would it still be possible to use the react-native upload command if the release tags were correctly configured?

`datadog-ci react-native upload`

https://github.com/DataDog/datadog-ci/tree/master/src/commands/react-native#upload

**Comment by louiszawadzki** [comment]
Hi @andrewjack-cat, indeed you should be able to sent the sourcemap with the `datadog-ci react-native upload` correctly configured.

As we match errors with sourcemaps based on their version (and with the highest build number), I would recommend to set a specific version for each EAS Update. For instance, if your app is in version `2.1.4` and you are doing the 3rd EAS Update the version could be `2.1.4-eas.v3`.

You will need to set this version when uploading the sourcemap and when initializing the SDK by using the `versionSuffix` parameter to `eas.v3` (the dash `-` will be added automatically by the SDK).

Let me know if this works for you!

**Comment by rogerfuentes** [comment]
I'm having a similar issue with this. The problem right now is not only that expo-updates uses `expo export` to generates a HBC file (Hermes Bytecode) which is uploaded, but also the name of the bundle in the code is loaded from a different folder (`.expo-internal`) and it uses a hash in the name to manage and track different versions. These 2 factors breaks the mapping between the source code and the source map (since RUM uses bundle_name to do that).

**Comment by rogerfuentes** [comment]
@louiszawadzki any updates on this? Source maps don't work at all with `expo-updates` or HBC files.

**Comment by seanadkinson** [comment]
Thank you @viernullvier, your `errorEventMapper` was the key to getting this to work for me.  By rewriting the stacktraces, datadog is able to properly match the source maps, and give me the correct location in code that the error occurred in.  Much appreciated.

**Comment by ali-pepperstone** [comment]
Can someone please help me understand , if we are not using EAS build. We are only using eas update. Do I need to build and upload the sourcemaps manually after a bare-bone build, then also when an eas update happens I have to do the same thing?.

Thanks.

**Comment by vanstinator** [comment]
I love Datadog, and I love how easy the RUM library is to integrate with an Expo app. So thanks for all your great work!

I've been using https://github.com/expo/expo-github-action to do my builds, because it checks the repo fingerprint before determining whether to do a full build or merely issue an expo update. It doesn't make it impossible to implement the workaround described above, but it does make it more challenging. It would be awesome if expo-datadog could properly support EAS Updates so the workaround could be avoided entirely.

**Comment by NoZiL** [comment]
Hi, I'm looking to migrate from Sentry to Datadog but this feature seems to not be available yet.
Is there a way I can help?

**Comment by radko93** [comment]
@marco-saia-datadog that's for the update. I've seen the PR and it looks great, but the example disables Hermes. Is it compatible with Hermes then?

**Comment by renanmav** [comment]
Just bumped to v2.9.0 and updated my metro config. Will test soon if this fixes the sourcemapping on Datadog dashboard when a user has OTA installed.

**Comment by marco-saia-datadog** [comment]
Hello 👋 We have released [v2.10.0](https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.10.0) of our React Native SDK, and [v3.13.0](https://github.com/DataDog/datadog-ci/releases/tag/v3.13.0) of Datadog CI.

Please update both versions in your apps, as we have tackled an issue with Hermes iOS sourcemaps symbolication.

We look forward to hearing a feedback from you, and we hope all issues are solved now!

**Comment by Brian-Yeh** [comment]
@marco-saia-datadog can you provide specific guidance for how to get this working for EAS updates? After updating those packages and adding the Metro plugin, it doesn't appear to be working for us still.

<img width="1105" height="108" alt="Image" src="https://github.com/user-attachments/assets/3c51281d-20be-4996-9d05-e9809a194fa6" />

We still see this unminification failed banner on some of our errors, even though clicking on the "RUM Debug Symbols page" link shows that a sourcemap is available. 

Not sure if this is the reason, but in the stack trace we see `.expo-internal` instead of `main.jsbundle`:
```
Error: Aborted
	.expo-internal/474f35ef7ed648242a16e57b05af666f.bundle at line 1:727099
...
```

The way we try to upload source maps for EAS Updates is by doing the mapping of the hbc files and adding the `versionSuffix`, described in the [previous comment](https://github.com/DataDog/expo-datadog/issues/28#issuecomment-2167983595).

Any help would be appreciated, thanks!

**Comment by ahmadatallah** [comment]
I'm facing what @Brian-Yeh, sourcemaps were uploaded however I'm getting this note:

<img width="1303" height="113" alt="Image" src="https://github.com/user-attachments/assets/c08c180b-53de-4f77-a398-925b64408a7d" />

**Comment by marco-saia-datadog** [comment]
Hello 👋 

Starting from `@datadog/mobile-react-native@2.10.0` and `@datadog/datadog-ci@v3.13.0`, our SDK exports a Datadog Metro Plugin, which attaches a unique Debug ID to your application bundle and sourcemap.

This allows accurate symbolication of stacktraces on Datadog, and it makes it possible to upload multiple sourcemaps for the same combination of `[service, version, bundle_name, platform]`, which comes in handy for EAS updates.

Add it to your `metro.config.js` to allow for accurate symbolication of stacktraces on Datadog:

```js
// const { getDefaultConfig } = require("expo/metro-config");
const { getDatadogExpoConfig } = require("@datadog/mobile-react-native/metro");
// const config = getDefaultConfig(__dirname);
const config = getDatadogExpoConfig(__dirname);
module.exports = config;
```

### Handling EAS updates

**Create the EAS update**

- Run `eas update --channel  [channel-name]  --message  "[message]" ` as you normally would
- A `dist` folder will be generated at the root of your project

**Locate the sourcemaps**
Look inside the dist folder and locate bundles and sourcemaps:
  - e.g. - `./dist/_expo/static/js/ios` and `./dist/_expo/static/js/android`
  - You will find a pair of files:
    - `.hbc` (bundle) and `.hbc.map` (sourcemap) for Hermes
    - `.js` or `.jsbundle` (bundle) and `*.map` (sourcemap) for JSC

**Upload the sourcemaps**
Make sure you have the latest version of datadog-ci installed, then for each platform (Android & iOS) use `datadog-ci` to upload the new debug symbols:

```sh
  npx datadog-ci react-native upload \
		--platform [ios OR android] \
		--service com.example.service \
		--bundle [BUNDLE_FILE] \
		--sourcemap [SOURCEMAP_FILE] \
		--release-version [YOUR_RELEASE_VERSION] \
		--build-version [YOUR_BUILD_VERSION]
```

The sourcemaps include a unique debug ID that is generated from the bundle’s contents. Because of this, the ID will change with every EAS update. As a result, even if the service, release, and build version remain the same, Datadog will still receive a new sourcemap upload.

We will update the documentation to include these instructions.

In the meantime, feel free to reach out if you encounter any further issues!

**Comment by marco-saia-datadog** [comment]
Hi @Brian-Yeh , thanks for your patience! 

Unfortunately, we haven't been able to reproduce this issue. From what we can tell, the underlying problem seems to be that matching sourcemaps cannot be found for your errors. However, this is a bit unusual since the `debugId` appears to be correctly injected into your sourcemap and bundle, and the upload via `datadog-ci` looks successful.

To move forward, I recommend reaching out to our support team, and mentioning this GH issue, so that the issue will be directly assigned to me.

With temporary access to your dashboard, I'll be able to investigate more closely and assist you in resolving the issue.
